//! Validate computed values match Python RNS reference.
//!
//! Loads `tests/interop/computed_vectors.json` (generated by
//! `generate_computed_vectors.py` from the Python RNS library) and verifies
//! that every Rust computation function produces identical results.
//!
//! This catches the class of bug where Python computes a value dynamically
//! but Rust hardcodes it.

use serde_json::Value;

fn load_vectors() -> Value {
    let raw = include_str!("../../../tests/interop/computed_vectors.json");
    serde_json::from_str(raw).expect("Failed to parse computed_vectors.json")
}

// -----------------------------------------------------------------------
// MTU vectors: link_mdu, resource_sdu, hashmap_max_len
// -----------------------------------------------------------------------

#[test]
fn test_mtu_link_mdu() {
    let vectors = load_vectors();
    for v in vectors["mtu_vectors"].as_array().unwrap() {
        let mtu = v["mtu"].as_u64().unwrap() as usize;
        let expected_mdu = v["link_mdu"].as_u64().unwrap() as usize;
        let rust_mdu = rete_transport::compute_link_mdu(mtu);
        assert_eq!(
            rust_mdu, expected_mdu,
            "link_mdu mismatch at MTU={mtu}: rust={rust_mdu} python={expected_mdu}"
        );
    }
}

#[test]
fn test_mtu_resource_sdu() {
    let vectors = load_vectors();
    for v in vectors["mtu_vectors"].as_array().unwrap() {
        let mtu = v["mtu"].as_u64().unwrap() as usize;
        let expected_sdu = v["resource_sdu"].as_u64().unwrap() as usize;
        let rust_sdu = rete_transport::compute_resource_sdu(mtu);
        assert_eq!(
            rust_sdu, expected_sdu,
            "resource_sdu mismatch at MTU={mtu}: rust={rust_sdu} python={expected_sdu}"
        );
    }
}

#[test]
fn test_mtu_hashmap_max_len() {
    let vectors = load_vectors();
    for v in vectors["mtu_vectors"].as_array().unwrap() {
        let mtu = v["mtu"].as_u64().unwrap() as usize;
        let link_mdu = v["link_mdu"].as_u64().unwrap() as usize;
        let expected = v["hashmap_max_len"].as_u64().unwrap() as usize;
        let rust = rete_transport::hashmap_max_len(link_mdu);
        assert_eq!(
            rust, expected,
            "hashmap_max_len mismatch at MTU={mtu} (link_mdu={link_mdu}): rust={rust} python={expected}"
        );
    }
}

// -----------------------------------------------------------------------
// RTT vectors: keepalive, stale time, traffic timeout
// -----------------------------------------------------------------------

#[test]
fn test_rtt_keepalive() {
    let vectors = load_vectors();
    for v in vectors["rtt_vectors"].as_array().unwrap() {
        let rtt = v["rtt"].as_f64().unwrap() as f32;
        let expected_ka = v["keepalive_interval_s"].as_f64().unwrap();
        let expected_stale = v["stale_time_s"].as_f64().unwrap();

        let (rust_ka, rust_stale) = rete_transport::compute_keepalive(rtt);
        let ka_diff = (rust_ka as f64 - expected_ka).abs();
        let stale_diff = (rust_stale as f64 - expected_stale).abs();

        // Allow 1% tolerance for f32→f64 precision
        assert!(
            ka_diff < expected_ka * 0.01 + 0.01,
            "keepalive mismatch at RTT={rtt}: rust={rust_ka} python={expected_ka} diff={ka_diff}"
        );
        assert!(
            stale_diff < expected_stale * 0.01 + 0.01,
            "stale_time mismatch at RTT={rtt}: rust={rust_stale} python={expected_stale} diff={stale_diff}"
        );
    }
}

#[test]
fn test_rtt_traffic_timeout() {
    let vectors = load_vectors();
    for v in vectors["rtt_vectors"].as_array().unwrap() {
        let rtt = v["rtt"].as_f64().unwrap() as f32;
        let expected = v["traffic_timeout_ms"].as_f64().unwrap();

        let rust = rete_transport::compute_traffic_timeout_ms(rtt) as f64;
        let diff = (rust - expected).abs();

        assert!(
            diff < expected * 0.01 + 0.1,
            "traffic_timeout mismatch at RTT={rtt}: rust={rust} python={expected}"
        );
    }
}

// -----------------------------------------------------------------------
// Channel vectors: window tiers by RTT
// -----------------------------------------------------------------------

#[test]
fn test_channel_window_tiers() {
    use rete_transport::Channel;

    let vectors = load_vectors();
    for v in vectors["channel_vectors"].as_array().unwrap() {
        let rtt = v["rtt"].as_f64().unwrap();
        let expected_max = v["window_max"].as_u64().unwrap() as u16;
        let expected_initial = v["initial_window"].as_u64().unwrap() as u16;

        let mut ch = Channel::new();
        assert_eq!(
            ch.window(),
            expected_initial,
            "initial_window mismatch at RTT={rtt}"
        );

        // Simulate enough deliveries at this RTT to reach the target tier.
        // Python promotes after FAST_RATE_THRESHOLD (10) consecutive rounds
        // at the qualifying rate. We simulate 12 rounds to ensure promotion.
        // Each round: send one message, then deliver it (frees window slot).
        let rtt_f32 = rtt as f32;
        for i in 0..12u16 {
            let sent = ch.send(0, &[0x42]);
            assert!(sent.is_some(), "channel should accept message {i}");
            ch.mark_delivered(i, rtt_f32);
        }

        assert_eq!(
            ch.window_max(),
            expected_max,
            "window_max mismatch at RTT={rtt}: rust={} python={expected_max} (after 12 deliveries)",
            ch.window_max()
        );
    }
}

// -----------------------------------------------------------------------
// Hop vectors: establishment timeout
// -----------------------------------------------------------------------

#[test]
fn test_establishment_timeout() {
    let vectors = load_vectors();
    for v in vectors["hop_vectors"].as_array().unwrap() {
        let hops = v["hops"].as_u64().unwrap();
        let expected = v["establishment_timeout_s"].as_u64().unwrap();
        let rust = rete_transport::compute_establishment_timeout(hops);
        assert_eq!(
            rust, expected,
            "establishment_timeout mismatch at hops={hops}: rust={rust} python={expected}"
        );
    }
}

// -----------------------------------------------------------------------
// Consistency: default constants match the compute functions
// -----------------------------------------------------------------------

#[test]
fn test_link_mdu_constant_matches_compute() {
    // LINK_MDU (431) should equal compute_link_mdu(500)
    assert_eq!(
        rete_transport::LINK_MDU,
        rete_transport::compute_link_mdu(500),
        "LINK_MDU constant doesn't match compute_link_mdu(500)"
    );
}

#[test]
fn test_hashmap_default_matches_compute() {
    // HASHMAP_MAX_LEN_DEFAULT should equal hashmap_max_len(LINK_MDU)
    assert_eq!(
        rete_transport::HASHMAP_MAX_LEN_DEFAULT,
        rete_transport::hashmap_max_len(rete_transport::LINK_MDU),
        "HASHMAP_MAX_LEN_DEFAULT doesn't match hashmap_max_len(LINK_MDU)"
    );
}
